SciKit Learn Preprocessing

In [2]:
import numpy as np

In [4]:
from sklearn.preprocessing import MinMaxScaler

In [5]:
data = np.random.randint(0,100,(10,2))

In [6]:
data

array([[39, 75],
       [45, 88],
       [29, 22],
       [23, 22],
       [67, 67],
       [17, 92],
       [63, 71],
       [46, 83],
       [30, 81],
       [81, 21]])

In [7]:
scaler_model = MinMaxScaler()

In [8]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
scaler_model.fit(data)

C:\Users\user\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
scaler_model.transform(data)

array([[ 0.34375   ,  0.76056338],
       [ 0.4375    ,  0.94366197],
       [ 0.1875    ,  0.01408451],
       [ 0.09375   ,  0.01408451],
       [ 0.78125   ,  0.64788732],
       [ 0.        ,  1.        ],
       [ 0.71875   ,  0.70422535],
       [ 0.453125  ,  0.87323944],
       [ 0.203125  ,  0.84507042],
       [ 1.        ,  0.        ]])

In [11]:
scaler_model.fit_transform(data)

C:\Users\user\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.34375   ,  0.76056338],
       [ 0.4375    ,  0.94366197],
       [ 0.1875    ,  0.01408451],
       [ 0.09375   ,  0.01408451],
       [ 0.78125   ,  0.64788732],
       [ 0.        ,  1.        ],
       [ 0.71875   ,  0.70422535],
       [ 0.453125  ,  0.87323944],
       [ 0.203125  ,  0.84507042],
       [ 1.        ,  0.        ]])

In [14]:
import pandas as pd

In [15]:
 mydata = np.random.randint(0,101,(50,4))

In [16]:
mydata

array([[ 85,  45,  84,  48],
       [ 67,  43,  87,  88],
       [ 24,  16,  66,   6],
       [ 34,  43,  51,  59],
       [ 98,  62,  79,  66],
       [ 41,  91,  29,  17],
       [ 33,  36,  36,  10],
       [ 31,  14,  48,  59],
       [ 26,  51,  47,  57],
       [  6,  60,  63,  11],
       [ 14,  97,  82,  37],
       [ 31,  43,   8,  31],
       [ 43,  63,   9,  67],
       [ 89,  72,  17,  53],
       [ 53,  88,  27,  87],
       [ 94,  40,  88,  67],
       [ 14,  46,  36,  37],
       [ 95,  63,  90,  18],
       [ 29,  58,  61,  41],
       [ 21,  57,   3,  44],
       [ 44,  19,  88,  25],
       [ 19,  44,  77,  64],
       [ 27,  50,  62,  67],
       [ 78,  46,  77,  86],
       [ 75,  79,   2,  50],
       [ 97,   4,  99,  14],
       [  5,  90,  15,  32],
       [ 34, 100,  68,   4],
       [ 12,  35,  29,  85],
       [ 22,   9,  56,  26],
       [ 65,  61,  81,  22],
       [ 70,  38,  68,  41],
       [ 71,  33,  30,  30],
       [ 42,   1,  92,  52],
       [ 49,  

In [21]:
df = pd.DataFrame(data = mydata, columns = ['f1','f2','f3','label'])

In [22]:
df

f1   f2  f3  label
0   85   45  84     48
1   67   43  87     88
2   24   16  66      6
3   34   43  51     59
4   98   62  79     66
5   41   91  29     17
6   33   36  36     10
7   31   14  48     59
8   26   51  47     57
9    6   60  63     11
10  14   97  82     37
11  31   43   8     31
12  43   63   9     67
13  89   72  17     53
14  53   88  27     87
15  94   40  88     67
16  14   46  36     37
17  95   63  90     18
18  29   58  61     41
19  21   57   3     44
20  44   19  88     25
21  19   44  77     64
22  27   50  62     67
23  78   46  77     86
24  75   79   2     50
25  97    4  99     14
26   5   90  15     32
27  34  100  68      4
28  12   35  29     85
29  22    9  56     26
30  65   61  81     22
31  70   38  68     41
32  71   33  30     30
33  42    1  92     52
34  49   17  34     61
35  18   10  71     25
36  25   30   4     14
37  67   94  93     63
38  46   11  49     47
39  74   73  34      9
40   7   49  10     72
41  14   33  24     36
42  45   16  53     29
43  98   64  23     23
44  97   73  97     71
45  74   76  20     47
46  56   12  72     65
47  17   77  81     27
48  69   54   5     94
49  17   99  13     60

In [23]:
X = df[['f1','f2','f3']]

In [31]:
y = df['label']

In [32]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [36]:
X_train.shape

(35, 3)

In [38]:
X_test.shape

(15, 3)